apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-prod

images:
- name: ghcr.io/juhisxd/guestbook
  newName: ghcr.io/juhisxd/guestbook
  newTag: v0.0.1