apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: guestbook-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/juhisxd/guestbook:v1.4.0
        name: guestbook
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - configMap:
          name: guestbook-data
        name: data-volume
