apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: web-page-status
  namespace: kargo-advanced
spec:
  args:
  - name: stage
  metrics:
  - name: web page status
    interval: 5s
    count: 2
    successCondition: result < 200
    failureLimit: 2
    provider:
      web:
        url: http://{{args.stage}}.guestbook.juho.relex.software/db
        headers:
          - key: Content-Type
            value: application/json
        jsonPath: "{$.posts}"
