apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: web-page-status
  namespace: kargo-advanced
spec:
  args:
  - name: stage
  metrics:
  - name: web page status
    interval: 5s
    count: 2
    failureLimit: 2
    provider:
      web:
        url: http://{{args.stage}}.guestbook.juho.relex.software/
        headers:
          - key: Content-Type
            value: application/json
        jsonPath: "{$}"
  - name: debug-url
    provider:
      job:
        spec:
          template:
            spec:
              containers:
                - name: debug
                  image: curlimages/curl:latest
                  command: [ "sh", "-c", "echo 'Debug URL: http://{{args.stage}}.guestbook.juho.relex.software/env' && curl -v http://{{args.stage}}.guestbook.juho.relex.software/env" ]
              restartPolicy: Never
    successCondition: "true"

