apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
#  verification:
#    analysisTemplates:
#      - name: web-page-status
#    args:
#      - name: stage
#        value: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    analysisTemplates:
      - name: web-page-status
    args:
      - name: stage
        value: staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ab-test-a
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
  verification:
    analysisTemplates:
      - name: web-page-status
    args:
      - name: stage
        value: ab-test-a
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - ab-test-a
  verification:
    analysisTemplates:
      - name: web-page-status
    args:
      - name: stage
        value: prod