apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-dev

images:
- name: YOUR_IMAGE_NAME
  newName: ${IMAGE_NAME}
  newTag: ${IMAGE_TAG}

patches:
- target:
    kind: HTTPRoute
    name: guestbook-route
  patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: dev.guestbook.juho.relex.software