apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-dev

images:
- name: YOUR_IMAGE_NAME
  newName: ${IMAGE_NAME}
  newTag: ${IMAGE_TAG}
spec:
  hostnames:
    - "dev.guestbook.juho.relex.software"
