apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/juhisxd/guestbook:latest
        name: guestbook
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: RESPONSE_FORMAT
          value: "json"
        - name: CONTENT_TYPE
          value: "application/json"
        - name: ENABLE_JSON_RESPONSE
          value: "true"