#apiVersion: v1
#kind: Service
#metadata:
#  name: guestbook
#spec:
#  selector:
#    app: guestbook
#  ports:
#    - name: http
#      port: 80
#      targetPort: http

apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook