apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: ghcr.io/juhisxd/guestbook:latest
        name: guestbook
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        configMap:
          name: guestbook-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-data
data:
  db.json: |
    {
      "posts": [
        { "id": 1, "title": "guestbook", "author": "typicode" }
      ],
      "comments": [
        { "id": 1, "body": "some comment", "postId": 1 }
      ],
      "profile": {
        "name": "typicode"
      }
    }
---