apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-staging

images:
- name: ${{ vars.image }}
  newTag: ${{ imageFrom(vars.image).Tag }}

patches:
- target:
    kind: HTTPRoute
    name: guestbook-route
  patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: staging.guestbook.juho.relex.software